### ISSUE TITLE
**LOGIN**: Tried to input invalid username and password but prompted a successful message

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#1]
I've tried to input an invalid username and password and I was expecting to prompt a message that my username and password did not match but then the message is still a successful message :dizzy_face:

![image](https://user-images.githubusercontent.com/34019450/54400284-108f2e80-46fd-11e9-9aca-d46f10aa2c31.png)

**Comment by kyango** [comment]
Resolve issue by implementing an error message and deleting icon for unnecessary spaces.

**Comment by mquijom** [comment]
Kindly use this message and color.

![image](https://user-images.githubusercontent.com/34019450/54572916-cc659c00-4a24-11e9-8e72-80668247c370.png)

**Comment by kyango** [comment]
Version v0.1.16
file views/login.vue
change the color of the warning & message (Invalid UserCredentials)

**Comment by kyango** [comment]
Version v0.1.17
file views/login.vue
change the color of the warning & message (Invalid UserCredentials)
