### ISSUE TITLE
Admin module is not for approver only. Do not use `Approver` as label to First Column.

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#10]
And also in adding data, the label is still Approver.

![image](https://user-images.githubusercontent.com/34019450/54404362-2bb66a00-470e-11e9-9c96-31e37bce6fb6.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.18
- File Path: fda-admin-portal/src/views/app/accounts/group.vue
- Resolution:
   - Remove Approver Label in first column.
![add admin](https://user-images.githubusercontent.com/34052250/54655447-eb376180-4afc-11e9-8e94-13590ca4600b.PNG)

**Comment by mquijom** [comment]
Verified this issue
