### ISSUE TITLE
Admin Table viewing details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#11]
The title should not "View Location". It is "**Admin Details**" or maybe you can set **admin's name** as the title.
And also the label for admin's name is not "Approver Name", "**Name**" is acceptable.
Group Name column should display the **group's name** not the _id,
And last, the design should in proper design not in table template.

![image](https://user-images.githubusercontent.com/34019450/54404613-168e0b00-470f-11e9-979a-695a846bc10e.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/accounts/admin.vue
- Resolution:
   - Remove password field.
   - Adding missing data.
![adminNew](https://user-images.githubusercontent.com/34052250/54674214-eabbbc80-4b36-11e9-8c9e-165a802edf3d.PNG)

**Comment by mquijom** [comment]
Relating this issue to #57

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...

**Comment by kyango** [comment]
Done testing
