### ISSUE TITLE
Products must prevent to add/edit with the same details or null data

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#12]
tested by @godofuri76

**Comment by kyango** [comment]
Version: v0.1.20
Files: app/reference/product
Resolution: Add warning and success notification for null fields and same value.

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result

![products](https://user-images.githubusercontent.com/34052250/55049208-3d8cfb00-5086-11e9-9afe-0718f06fe3b9.PNG)
![products2](https://user-images.githubusercontent.com/34052250/55049210-3d8cfb00-5086-11e9-8da1-dccb4facca40.PNG)
