### ISSUE TITLE
Editing Admin user data

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#14]
Group name existing value is missing.
Password should not be modified by admin

![image](https://user-images.githubusercontent.com/34019450/54406048-91f1bb80-4713-11e9-8af0-86261b303384.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/accounts/admin.vue
- Resolution:
  - Remove password field.
 - Adding missing data.
![adminNew](https://user-images.githubusercontent.com/34052250/54674027-83057180-4b36-11e9-8f2b-e9e2cef418fd.PNG)

**Comment by mquijom** [comment]
Relating this issue to #82
