### ISSUE TITLE
Adding admin user with password is restricted

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#15]
![image](https://user-images.githubusercontent.com/34019450/54406336-bd28da80-4714-11e9-914d-e1234b380133.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/accounts/admin.vue
- Resolution:
  - Remove password field.
![AddADMIN](https://user-images.githubusercontent.com/34052250/54665389-eb962380-4b21-11e9-9f9d-f32f6dc87324.PNG)

**Comment by mquijom** [comment]
Password is already not visible in form but setting password is still required but in my opinion, it must be in email request. Relate this issue to #82
