### ISSUE TITLE
Products Table

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#18]
**Scenario: Product Table**

- Expected Result
- [ ] Fields: 
Product Name
Created By
Date Created
Modified By
Date Modified

- Actual Result
**Created By**, **Modified By** and **Date Modified** is missing

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/product.vue
- Resolution:
   Adding missing data.
![products](https://user-images.githubusercontent.com/34052250/54656174-9a753800-4aff-11e9-98d6-0184974efdd2.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
