### ISSUE TITLE
Session did not stored after logging in.

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#2]
The **session did not stored after I login**, When I **refresh** the browser, I have been **routed** to login portal and cannot get back to dashboard again.

**Comment by abalita** [comment]
- Fixed. For testing v0.1.24
- Modified file(s): fda-admin-portal/src/store/index.js
- Resolution:
Modified store plugins

`export default new Vuex.Store({
  modules,
  strict: process.env.NODE_ENV !== "production",
  plugins: [
    createPersistedState({
      key: "fda-admin-reference",
      paths: [
        "admin_tables",
        "breadcrumbs",
        "changePassword_tables",
        "checklist_tables",
        "notification",
        "checklist_tables",
        "client_table",
        "designation_tables",
        "fees_tables",
        "group_table",
        "identification_tables",
        "product_line_tables",
        "profile_tables",
        "reference_tables",
        "regional_tables",
        "task_tables"
      ]
    }),
    //store user session in cookies
    createPersistedState({
      key: "fda-admin-session",
      paths: ["user_session"],
      storage: {
        getItem: key => Cookies.get(key),
        setItem: (key, value) =>
          Cookies.set(key, value, { expires: 1, secure: false }),
        removeItem: key => Cookies.remove(key)
      }
    })
  ]
});`

**Comment by VPBelo** [comment]
Closing this issue.
