### ISSUE TITLE
Primary Table

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#20]
**Scenario: Primary Table**

- Expected Result
- [ ] Fields: 
Primary Type
Created By
Date Created
Modified By
Date Modified

- Actual Result
**Created By**, **Modified By** and **Date Modified** is missing

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/primary.vue
- Resolution:
   - Adding missing data.
![primary label](https://user-images.githubusercontent.com/34052250/54656410-78c88080-4b00-11e9-8ee9-3ca1adcbc192.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
