### ISSUE TITLE
Primary must prevent to add/edit with the same details or null data

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#22]
**Scenario: Adding or editing data in primary with null fields or same value**

- Expected Result
- [ ]   Error with validation

- Actual Result
No validation

**Comment by kyango** [comment]
Version: v0.1.21
Files: app/reference/primary
Resolution: Add warning and success notification for null fields and same value. and fix core service data to be passed has different name it should be a data no (new_primary)

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result

![primary](https://user-images.githubusercontent.com/34052250/55049536-9b6e1280-5087-11e9-8f60-eb17ef28c5c2.PNG)
![primary2](https://user-images.githubusercontent.com/34052250/55049537-9c06a900-5087-11e9-85e5-c15a142460bf.PNG)
