### ISSUE TITLE
Additional Table View Details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#23]
**Scenario: Viewing more details of Additional data**

- Expected Result
- [ ]  Title: View Details

- [ ]  Fields:
Additional Activity
Created By
Date Created
Modified By
Date Modified

- Actual Result
Title: View Location
Fields: Name, Date Created
Missing Fields: Created By, Modified By, Date Modified

- Remarks
Date should be formatted as MM DD, YYYY
Design should not in table template.

![image](https://user-images.githubusercontent.com/34019450/54416831-769aa680-473b-11e9-88b2-989d3a5fd352.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/addditionalActivity.vue
- Resolution:
  - Adding missing data.
![additional](https://user-images.githubusercontent.com/34052250/54656647-669b1200-4b01-11e9-9e05-7db38cf59761.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
