### ISSUE TITLE
Additional Table

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#24]
**Scenario: Additional Table**

- Expected Result
- [ ]  Fields:
Additional Activity
Created By
Date Created
Modified By
Date Modified

- Actual Result
Missing Fields: Created By, Modified By, Date Modified

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/additionalActivity.vue
- Resolution:
  - Adding missing data.
![additional](https://user-images.githubusercontent.com/34052250/54656691-9c3ffb00-4b01-11e9-95e7-be1d2008bcc5.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
