### ISSUE TITLE
Additional Table does not have a notification after adding or editing data

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#25]
**Scenario: Adding or editing data from Additional Table**

- Expected Result
- [x]  Notify a response message

- Actual Result
No notification

**Comment by mquijom** [comment]
Closed due duplicated issue

**Comment by kyango** [comment]
Version v0.1.16
Add notification message

**Comment by mquijom** [comment]
Verified that Additional Table has already notification in **version 0.1.16**
