### ISSUE TITLE
Additional must prevent to add/edit with the same details or null data

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#26]
**Scenario: Adding or editing additional data with null values or existing values**

- Expected Result
- [ ]  Error with validation

- Actual Result
No validation

**Comment by kyango** [comment]
Version: v0.1.20
Files: app/reference/additionalActivity
Resolution: Add warning and success notification for null fields and same value.

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result

![additional](https://user-images.githubusercontent.com/34052250/55049123-d3745600-5085-11e9-967c-a2936f582112.PNG)
![additionalvalidate](https://user-images.githubusercontent.com/34052250/55049124-d40cec80-5085-11e9-80a9-73e898cc958e.PNG)
