### ISSUE TITLE
Declared Capital Table

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#27]
**Scenario: View Declared Capital's data**

- Expected Result
- [ ]  Fields:
Declared Capital
Created By
Date Created
Modified By
Date Modified

- Actual Result
Missing Fields: Created By, Modified By, Date Modified

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/capital.vue
- Resolution:
 - Adding missing data.
![capital](https://user-images.githubusercontent.com/34052250/54659039-39536180-4b0b-11e9-9fea-ffd720fb2cfc.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
