### ISSUE TITLE
Declared Capital Table View Details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#29]
**Scenario: Viewing more details of Declared Capital's data**

- Expected Result
- [ ]  Title: View Details

- [ ]  Fields:
Declared Capital
Created By
Date Created
Modified By
Date Modified

- Actual Result
Title: View Location
Fields: Name, Date Created
Missing Fields: Created By, Modified By, Date Modified

- Remarks
Date should be formatted as MM DD, YYYY
Design should not in table template.

![image](https://user-images.githubusercontent.com/34019450/54469869-5a4d4700-47d9-11e9-9967-d67919960d96.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/capital.vue
- Resolution:
  - Adding missing data.
![declared](https://user-images.githubusercontent.com/34052250/54658896-939ff280-4b0a-11e9-8cd5-35de5781e8b5.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
