### ISSUE TITLE
Client User Table does not have a View Details function.

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#3]
Please implement **Viewing More details** in client user table so we can review more details about client.

**Comment by Wandelacruz** [comment]
**Deployment version 0.1.20**
**File path: fda-admin-portal/src/views/app/accounts/client.vue**
Resolution:
- [ ] added a more detailed page for each client.

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result
![Clients](https://user-images.githubusercontent.com/34052250/55048443-239de900-5083-11e9-9470-2548dfa14c0f.PNG)
