### ISSUE TITLE
Declared Capital must prevent to add/edit with the same values or null data

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#30]
**Scenario: Adding or editing data in declared capital with null fields or same value**

- Expected Result
- [ ]   Error with validation

- Actual Result
No validation

**Comment by kyango** [comment]
Version: v0.1.20
Files: app/reference/capital
Resolution: Add warning and success notification for null fields and same value.

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result

![declared](https://user-images.githubusercontent.com/34052250/55049270-7d53e280-5086-11e9-9613-f47c72c6c03c.PNG)
![declared2](https://user-images.githubusercontent.com/34052250/55049274-7dec7900-5086-11e9-967b-9b9187f3fe2a.PNG)
