### ISSUE TITLE
Product Line Table View Details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#33]
**Scenario: Viewing more details of Product Line's data**

- Expected Result
- [ ]  Title: View Details
- [ ]  Fields:
Product Line
Product Type
Status
Created By
Date Created
Modified By
Date Modified

- Actual Result
Title: View Location
Fields: Name, Date Created
Missing Fields: Created By, Date Created, Modified By, Date Modified

- Remarks
Date should be formatted as MM DD, YYYY
Design should not in table template.

- Suggested Solutions:
Add the missing fields to model schema then call it to display
Use `formatDate(date, type)` to format the date. It can be found at `src/plugins/mixins.js`

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/productLine.vue
- Resolution:
  - Adding missing data.
![productLine](https://user-images.githubusercontent.com/34052250/54660210-6c4c2400-4b10-11e9-9889-e34f58938e7a.PNG)

**Comment by mquijom** [comment]
Please format the **Status** 
**0** - **Active**
**1** - **Inactive**

Moving the rest issue to #84.
Please see the issue...

**Comment by VPBelo** [comment]
- For Testing in v0.1.20
- File Path: fda-admin-portal/src/views/app/reference/productLine.vue
- Resolution:
  - Adding missing data.
  - Format Status

![productLine](https://user-images.githubusercontent.com/34052250/54736916-6590e000-4be8-11e9-9913-bac2611cd5d6.PNG)
![productLine2](https://user-images.githubusercontent.com/34052250/54736917-6590e000-4be8-11e9-8268-b091edd194e8.PNG)

**Comment by kyango** [comment]
Closing this issue
