### ISSUE TITLE
Product Line must prevent to add/edit with the same values or null data

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#34]
**Scenario: Adding or editing data in product line with null fields or same value**

- Expected Result
- [ ]   Error with validation

- Actual Result
No validation

**Comment by kyango** [comment]
Version: v0.1.20
Files: app/reference/productLine
Resolution: Add warning and success notification for null fields and same value.

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result

![productLine](https://user-images.githubusercontent.com/34052250/55049362-ca37b900-5086-11e9-81d6-0247cd3f96d3.PNG)
![productLine2](https://user-images.githubusercontent.com/34052250/55049363-ca37b900-5086-11e9-9089-39ff874c5e0b.PNG)
