### ISSUE TITLE
Province Table

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#36]
**Scenario: View Province's data**

- Expected Result
- [ ]  Fields:
Region Name
Province Name
Created By
Date Created
Modified By
Date Modified

- Actual Result
Missing Fields: Created By, Modified By

- Suggest Solution:
Missing fields is already on model schema but not visible on design

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/location/province.vue
- Resolution:
  - Adding missing data.
![province](https://user-images.githubusercontent.com/34052250/54660526-c00b3d00-4b11-11e9-89b1-459ba26b9703.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
