### ISSUE TITLE
Province Table View Details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#37]
**Scenario: Viewing more details of Province's data**

- Expected Result
- [ ]  Title: View Details
- [ ]  Fields:
Region Name
Province Name
Created By
Date Created
Modified By
Date Modified

- Actual Result
Title: View Location
Fields: Region Name, Province Name, Date Created, Modified Date
Missing Fields: Created By, Modified By 

- Remarks
Date should be formatted as MM DD, YYYY
Design should not be in table template.

- Suggested Solutions:
Missing fields is already on model schema but not visible to design
Use `formatDate(date, type)` to format the date. It can be found at `src/plugins/mixins.js`

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/location/province.vue
- Resolution:
  - Adding missing data.
![province](https://user-images.githubusercontent.com/34052250/54660635-21331080-4b12-11e9-9a8f-f85bfb4a5fb2.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
