### ISSUE TITLE
Sidebar menu label is truncated

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#4]
Sidebar menu text must not truncated

![image](https://user-images.githubusercontent.com/34019450/54402468-0b36e180-4707-11e9-8672-259abee61024.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.16
- https://fda-admin-portal.herokuapp.com/#/app
- Description: remove manager word from side bar menu to be not truncated.
![mmmmmm](https://user-images.githubusercontent.com/34052250/54516529-20776e80-499a-11e9-950c-8d4915d1e7fd.PNG)
