### ISSUE TITLE
Region Table

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#40]
**Scenario: View Region's data**

- Expected Result
- [ ]  Fields:
Region Name
Region Code
Created By
Date Created
Modified By
Date Modified

- Actual Result
Missing Fields: Created By, Modified By

- Suggest Solution:
Missing fields is already on model schema but not visible on design

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/location/region.vue
- Resolution:
  - Adding missing data.
![region](https://user-images.githubusercontent.com/34052250/54660910-3197bb00-4b13-11e9-945d-3bcaf0244e3d.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...

**Comment by VPBelo** [comment]
- For Testing in v0.1.20
- File Path: fda-admin-portal/src/views/app/location/region.vue
- Resolution:
  -Adding missing data.
![RegionNew](https://user-images.githubusercontent.com/34052250/54734037-117dff80-4bd8-11e9-9b92-5031cfb4b2ed.PNG)
