### ISSUE TITLE
Region Table View Details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#41]
**Scenario: Viewing more details of Region's data**

- Expected Result
- [ ]  Title: View Details
- [ ]  Fields:
Region Name
Region COde
Created By
Date Created
Modified By
Date Modified

- Actual Result
Title: View Location
Fields: Region Name, Region Code, Date Created, Modified Date
Missing Fields: Created By, Modified By 

- Remarks
Date should be formatted as MM DD, YYYY
Design should not be in table template.

- Suggested Solutions:
Missing fields is already on model schema but not visible to design
Use `formatDate(date, type)` to format the date. It can be found at `src/plugins/mixins.js`

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/location/region.vue
- Resolution:
  - Adding missing data.
![region](https://user-images.githubusercontent.com/34052250/54660947-5a1fb500-4b13-11e9-94d6-00a865363944.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
