### ISSUE TITLE
Region must prevent to add/edit data with the same details or null values 

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#42]
**Scenario: Adding or editing data in region with null fields or same value**

- Expected Result
- [ ]   Error with validation

- Actual Result
No validation

**Comment by kyango** [comment]
Version:  v0.1.19
Files: app/location/region
Resolution: Add warning and success notification for null fields and same value.

**Comment by mquijom** [comment]
Region can now validate fields but already in error state.
