### ISSUE TITLE
City Table

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#44]
**Scenario: View data of City**

- Expected Result
- [ ]  Fields:
City/Municipality
Region Name
Province Name
Created By
Date Created
Modified By
Date Modified

- Actual Result
Missing Fields: Created By, Modified By

- Suggest Solution:
Missing fields is already on model schema but not visible on design

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/location/city.vue
- Resolution:
  - Adding missing data.
![city](https://user-images.githubusercontent.com/34052250/54661241-5d677080-4b14-11e9-985c-af71f81a278a.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
