### ISSUE TITLE
City Table View Details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#45]
**Scenario: Viewing more details of City's data**

- Expected Result
- [ ]  Title: View Details
- [ ]  Fields:
City/Municipality
Region Name
Province Name
Created By
Date Created
Modified By
Date Modified

- Actual Result
Title: View Location
Missing Fields: Created By, Modified By 

- Remarks
Date should be formatted as MM DD, YYYY
Design should not be in table template.

- Suggested Solutions:
Missing fields is already on model schema but not visible to design
Use `formatDate(date, type)` to format the date. It can be found at `src/plugins/mixins.js`

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/location/city.vue
- Resolution:
  - Adding missing data.
![city](https://user-images.githubusercontent.com/34052250/54661283-8982f180-4b14-11e9-807b-8efb2cdea1f5.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...
