### ISSUE TITLE
Group management with only one child

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#5]
I think having group menu outside the dropdown should be fine.

![image](https://user-images.githubusercontent.com/34019450/54402750-26562100-4708-11e9-9780-3c0d3396cb0f.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.18
- File Path: fda-admin-portal/src/views/app/accounts/group.vue
- Resolution:
   - Remove Group Menu Dropdown.
![groups](https://user-images.githubusercontent.com/34052250/54655204-005fc080-4afc-11e9-9ba3-d12306f2dcd2.PNG)
