### ISSUE TITLE
Task must prevent to add/edit data with the same details or null values

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#51]
**Scenario: Adding or editing data in task with null fields or same value**

- Expected Result
- [ ]   Error with validation

- Actual Result
No validation

**Comment by kyango** [comment]
Version: v0.1.22
Files: app/task/task
Resolution: Add warning and success notification for null fields and same value.

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result
![taskValidate](https://user-images.githubusercontent.com/34052250/55048951-141f9f80-5085-11e9-95f1-9de108fb0ca7.PNG)
