### ISSUE TITLE
Checklist Table

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#53]
**Scenario: View data of Checklist**

- Expected Result
- [ ]  Fields:
Description
Task Name
Created By
Date Created
Modified By
Date Modified

- Actual Result
Missing Fields: Created By, Modified By

- Suggest Solution:
Missing fields is already on model schema but not visible on design

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/task/checklist.vue
- Resolution:
  - Adding missing data.
![checklist](https://user-images.githubusercontent.com/34052250/54663209-6c9dec80-4b1b-11e9-934a-5e50d6ecd300.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving to issue #84
