### ISSUE TITLE
Checklist must prevent to add/edit data with the same details or null values

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#55]
**Scenario: Adding or editing data in checklist with null fields or same value**

- Expected Result
- [ ]   Error with validation

- Actual Result
No validation

**Comment by kyango** [comment]
Version: v0.1.20
Files: app/task/checklist
Resolution: Add warning and success notification for null fields and same value.

**Comment by VPBelo** [comment]
**Issue:** Success adding data with same value.

**- Actual Result**
![checklist](https://user-images.githubusercontent.com/34052250/55049453-39ada880-5087-11e9-9a4b-9f0be06c8c0a.PNG)
![checklist2](https://user-images.githubusercontent.com/34052250/55049454-39ada880-5087-11e9-8418-1ae2e564af1d.PNG)

**Comment by VPBelo** [comment]
- For Testing in v0.1.24
- File Path: fda-admin-portal/src/views/app/task/checklist.vue
- Resolution:
 - Add warning and success notification same value.
![checklist2](https://user-images.githubusercontent.com/34052250/55064414-e81c1280-50b4-11e9-95cb-4cea7f9f4ad5.PNG)

**Comment by VPBelo** [comment]
Closing this issue.
