### ISSUE TITLE
Checklist does not have a notification after adding or editing data

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#56]
**Scenario: Adding or editing data in checklist**

- Expected Result
- [x]   Notify a successful or unsuccessful message

- Actual Result
No notification

**Comment by kyango** [comment]
Version v0.1.16
Add notification message add and edit checklist

**Comment by mquijom** [comment]
Verified that checklist has already notification in **version 0.1.16**
