### ISSUE TITLE
Group Collection Schema

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#57]
- Expected Schema
`status type` should be either `0` or `1` that means Active or Inactive and the default should be `0`. Or set the type to `Boolean` and the default should be `false`.
The `created_by` field must not have default.

- Actual Result
`status` with `String` type and the default set as `Active`.
`created_by` with a default value.
`modified_by` is missing.

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/accounts/admin.vue
- Resolution:
   - Adding missing data.
![adminNew](https://user-images.githubusercontent.com/34052250/54674952-7255fb00-4b38-11e9-9e55-eaf8166424ae.PNG)

**Comment by mquijom** [comment]
**Created By** and **Modified By** is not a date but a user. 
- [ ] **Created By** is a user who created the data.
- [ ] **Modified By** is a user who last modified the data.
- [ ] **Date Modified** is when the data is modified.

- Suggested Solution:
Assign `id` from token to `created_by` or `modified_by`
Use `pre findOneAndUpdate` for date modified

**Comment by mquijom** [comment]
Closing this issue and moving to issue #84
