### ISSUE TITLE
Group Table View Details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#58]
**Scenario: Viewing more details of Checklist's data**

- Expected Result
- [ ]  Title: View Details
- [ ]  Fields:
Group Name
Status
Created By
Date Created
Modified By
Date Modified

- Actual Result
Title: View Location
Missing Fields: Modified By 

- Remarks
Date should be formatted as MM DD, YYYY
Design should not be in table template.

- Suggested Solutions:
Use `formatDate(date, type)` to format the date. It can be found at `src/plugins/mixins.js`

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/accounts/group.vue
- Resolution:
  - Adding missing data.
![group](https://user-images.githubusercontent.com/34052250/54663500-69573080-4b1c-11e9-9451-1660c72e3888.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving to issue #84
