### ISSUE TITLE
Group must prevent to add/edit data with the same details or null values

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#59]
**Scenario: Adding or editing data in group with null fields or same value**

- Expected Result
- [ ]   Error with validation

- Actual Result
No validation

**Comment by kyango** [comment]
Version: v0.1.20
Files: app/group
Resolution: Add warning and success notification for null fields and same value.

**Comment by VPBelo** [comment]
**Issue:** Success adding data with same value and null fields.

**- Actual Result**
![AdminError](https://user-images.githubusercontent.com/34052250/55048795-7af08900-5084-11e9-8164-cc6c66022395.PNG)
![AdminValidate](https://user-images.githubusercontent.com/34052250/55048796-7b891f80-5084-11e9-9f2f-9f50844e899f.PNG)

**Comment by VPBelo** [comment]
- For Testing in v0.1.24
- File Path: fda-admin-portal/src/views/app/accounts/group.vue
- Resolution:
 - Add warning and success notification in same value.

![GroupNew](https://user-images.githubusercontent.com/34052250/55063493-0b45c280-50b3-11e9-85f9-5cc1d3dbba0b.PNG)

**Comment by VPBelo** [comment]
Closing this issue.
