### ISSUE TITLE
Logout with confirmation

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#6]
Please implement a confirmation before logging out.

**Comment by VPBelo** [comment]
- For Testing in v0.1.16
- File Path: fda-admin-portal/src/layout/UserLayout.vue
- Resolution:
- [ ] Adding a confirmation before logging out.
![out](https://user-images.githubusercontent.com/34052250/54581833-4445bd80-4a49-11e9-88c1-2d630018bd46.PNG)
