### ISSUE TITLE
Designation Table/ Designation Model

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#61]
**Scenario: View data of Designation**

- Expected Result
- [ ]  Fields:
Designation Name
Created By
Date Created
Modified By
Date Modified

- Actual Result
Missing Fields: Created By, Modified By, Date Modified

- Suggest Solution:
Add the missing field to model schema and display it to design

- Question
What is the purpose of `status` and `type` in model schema?
If the fields is still in used, I thinks you should include it also.

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/designation.vue
- Resolution:
  - Adding missing data.
![Designation](https://user-images.githubusercontent.com/34052250/54663998-f9e24080-4b1d-11e9-8b29-d4e5774311cf.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving to issue #84
