### ISSUE TITLE
Designation Table View Details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#62]
**Scenario: Viewing more details of Designation's data**

- Expected Result
- [ ]  Title: View Details
- [ ]  Fields:
Designation Name
Created By
Date Created
Modified By
Date Modified

- Actual Result
Title: View Location
Missing Fields: Created By, Modified By, Date Modified

- Remarks
Date should be formatted as MM DD, YYYY
Design should not be in table template.

- Suggested Solutions:
Add the missing fields to model schema and display it on design
Use `formatDate(date, type)` to format the date. It can be found at `src/plugins/mixins.js`

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/designation.vue
- Resolution:
   - Adding missing data.
![Designation](https://user-images.githubusercontent.com/34052250/54664285-c18f3200-4b1e-11e9-97fb-e39f337ccacf.PNG)

**Comment by mquijom** [comment]
Closing this issue and moving to issue #84
