### ISSUE TITLE
Designation must prevent to add/edit data with the same details or null values

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#63]
**Scenario: Adding or editing data in designation with null fields or same value**

- Expected Result
- [ ]   Error with validation

- Actual Result
No validation

**Comment by kyango** [comment]
Version: v0.1.20
Files: app/designation
Resolution: Add warning and success notification for null fields and same value.

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result
![Designation](https://user-images.githubusercontent.com/34052250/55049034-7b3d5400-5085-11e9-9c68-35a18ee2f17b.PNG)
![Designationvalidate](https://user-images.githubusercontent.com/34052250/55049036-7b3d5400-5085-11e9-8aec-d991816e5603.PNG)
