### ISSUE TITLE
Identification Table

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#65]
**Scenario: View data of Identification**

- Expected Result
- [ ]  Fields:
Identification Type
Created By
Date Created
Modified By
Date Modified

- Actual Result
Missing Fields: Created By, Modified By, Date Modified
`Date Created` must not in Real Time. The Date of some data set as the date I tested it.

- Suggest Solution:
Add the missing field to model schema and display it to design
Check the saved data in database if the date is in correct format.

![image](https://user-images.githubusercontent.com/34019450/54486099-3c0d4700-48be-11e9-9ea1-5301ace4902a.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/designation.vue
- Resolution:
   - Adding missing data.
![Designation](https://user-images.githubusercontent.com/34052250/54664436-28145000-4b1f-11e9-9db5-0008af87ae6c.PNG)

**Comment by mquijom** [comment]
Relating this issue to #66

**Comment by mquijom** [comment]
Closing this issue cause it is already existing
