### ISSUE TITLE
Identification Table View Details

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#66]
**Scenario: Viewing more details of Designation's data**

- Expected Result
- [ ]  Title: View Details
- [ ]  Fields:
Identification Type
Created By
Date Created
Modified By
Date Modified

- Actual Result
Title: View Location
Missing Fields: Identification Type, Created By, Modified By, Date Modified

- Remarks
Date should be formatted as MM DD, YYYY
Design should not be in table template.

- Suggested Solutions:
Add the missing fields to model schema and display it on design
Use `formatDate(date, type)` to format the date. It can be found at `src/plugins/mixins.js`

**Comment by VPBelo** [comment]
- For Testing in v0.1.19
- File Path: fda-admin-portal/src/views/app/reference/identification.vue
- Resolution:
  - Adding missing data.
![identification](https://user-images.githubusercontent.com/34052250/54664659-d7e9bd80-4b1f-11e9-9405-ad8f5ab2d78c.PNG)

**Comment by mquijom** [comment]
**Created By** and **Modified By** is not a date but a user.
Relating this issue to #57

**Comment by mquijom** [comment]
Closing this issue and moving the rest issue to #84.
Please see the issue...

**Comment by VPBelo** [comment]
- For Testing in v0.1.20
- File Path: fda-admin-portal/src/views/app/reference/identification.vue
- Resolution:
  - Adding missing data.
![identification](https://user-images.githubusercontent.com/34052250/54735628-34adac80-4be2-11e9-8c1f-f8bc447d2815.PNG)
