### ISSUE TITLE
My Profile fields

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#73]
**Scene: Updating my profile**

As of now, these are the **only** edited fields:
- Avatar
- First Name
- Last Name

- **Remarks**
Username and Emails must be a unique fields and **not** editable.

**Comment by abalita** [comment]
- Fixed. For Testing v0.1.25
- Modified file(s): 
fda-admin-portal/src/views/app/accounts/profile.vue
fda-services-accounts/api/models/AdminAccountsModel.js
- Resolution:
Added pre save and update validations in AdminAccountsModel
Added error handler on the frontend

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![adminProfile](https://user-images.githubusercontent.com/34052250/55203081-1c9ee400-5205-11e9-9568-d5ed46b15fd1.PNG)
