### ISSUE TITLE
Updating Profile Confirmation

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#74]
**Scene: Updating my profile**

- Expected Result
Updating with confirmation before to proceed

- Actual Result
No Confirmation

**Comment by VPBelo** [comment]
- For Testing in v0.1.17
- File Path: fda-admin-portal/src/views/app/accounts/profile.vue
- Resolution:
   Adding confirmation before to proceed to update details.
![qqqqqqwwwwwwwwwwwwwwwwww](https://user-images.githubusercontent.com/34052250/54586601-81657c00-4a58-11e9-976f-e3602adfc604.PNG)
