### ISSUE TITLE
Updating Profile with null fields

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#75]
**Scene: Updating my profile**

- Expected Result
Validating fields. Example: null fields

- Actual Result 
No Validation

**Comment by abalita** [comment]
- Fixed. for testing v0.1.24
- Modified file(s): fda-admin-portal/src/views/app/accounts/profile.vue
- Resolution:

Added form validation upon submission

`<v-form ref="form" v-model="valid">
                  <v-text-field
                  label="First Name"
                  v-model="admin.first_name"
                  required
                  :rules="[() => !!admin.first_name || 'This field is required']"
                ></v-text-field>
...
</v-form>`


script:
`showProfile() {
      this.$refs.form.validate()
      if(this.valid){
        this.show_profile = true;
      }else{
        this.$notifyError([{message:"Please fill-up required fields"}])
      }      
    }`

**Comment by VPBelo** [comment]
Closing this issue.
 - Actual Result

![password](https://user-images.githubusercontent.com/34052250/55059439-f0228500-50a9-11e9-8d36-e595c450ac59.PNG)
