### ISSUE TITLE
Password without Confirmation

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#77]
**Scene: Updating password**

- Expected Result
Updating with confirmation before to proceed

- Actual Result
No Confirmation

**Comment by VPBelo** [comment]
- For Testing in v0.1.17
- File Path: fda-admin-portal/src/views/app/passwordSettings/ChangePassword.vue
- Resolution:
   Adding confirmation before to proceed change password.
![password](https://user-images.githubusercontent.com/34052250/54587313-b96dbe80-4a5a-11e9-8858-2ab2aae7a150.PNG)

**Comment by mquijom** [comment]
Verified confirmation
