### ISSUE TITLE
Resetting password using email

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#78]
**Scene: Updating Password**

- Expected Result
Requesting `Change Password` using old password
Then Send a request link to my registered email.
And it will redirect to page that validate my password and confirm password then save.

- Actual Result
Changing password in my session

- Remarks
We are changing password by using request link for security purpose.

**Comment by mquijom** [comment]
Deployment Version: **0.1.21**

Files: 
- **fda-admin-portal/views/app/passwordSettings/ChangePassword.vue**
- **fda-admin-portal/views/app/passwordSettings/ResetPassword.vue**
- **fda-admin-portal/api/PasswordAPI**
- **fda-admin-portal/router.js**
- **fda-admin-portal/store/modules/user_session.js**
- **fda-services-accounts/api/routes/admin_router.js**

Remarks
Fixed by applying new design and architecture of password module.

![image](https://user-images.githubusercontent.com/34019450/54873675-98202000-4e16-11e9-842c-f7a232f79d24.png)

![image](https://user-images.githubusercontent.com/34019450/54873664-1af4ab00-4e16-11e9-878f-58c9fa312592.png)

**Comment by kyango** [comment]
Closed Issue
