### ISSUE TITLE
Not working menus

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#80]
- Questions
Are the menus still working or in used ?

- Maybe we might include these functionality under avatar menu using drop down menu:
- [ ] Change Profile
- [ ] Change Password
- [ ] Logout

![image](https://user-images.githubusercontent.com/34019450/54504438-9f56b200-496e-11e9-8410-a4956781aae8.png)

**Comment by VPBelo** [comment]
- For Testing in v0.1.16
- Adding drop down menu for:
- [ ] Change Profile
- [ ] Change Password
- [ ] Logout
![rrrrrrrrrrrrrrrrrrrrrr](https://user-images.githubusercontent.com/34052250/54581099-1f9c1680-4a46-11e9-8e8c-18d1f500d6f8.PNG)

**Comment by mquijom** [comment]
What is the use of notification? Is it still in used ?

**Comment by mquijom** [comment]
Please remove the notification icon for the mean time.
