### ISSUE TITLE
Side bar menu style

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#81]
- A **constant icons**
- An inconsistent text style: color, font weight

![image](https://user-images.githubusercontent.com/34019450/54504735-cc579480-496f-11e9-81b1-79d5d103a6dc.png)

**Comment by Wandelacruz** [comment]
- Deployment version 0.1.20
- File path: fda-admin-portal/src/layout/UserLayout.vue
- Resolution:
- [ ] consistent icons, font-weight, color
- [ ] added tooltip

**Comment by kyango** [comment]
Closing this issue
