### ISSUE TITLE
Created By and Modified By

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#84]
**Created By** and **Modified By** is not a date but a user. 
- [ ] **Created By** is a user who created the data.
- [ ] **Modified By** is a user who last modified the data.
- [ ] **Date Modified** is when the data is modified.

- Suggested Solution:
Assign `id` from token to `created_by` or `modified_by`
Use `pre findOneAndUpdate` for date modified

Below is the reference issues

**Comment by VPBelo** [comment]
- For Testing in v0.1.20
- Resolution:
   - Adding missing data for the reference above.

**Comment by kyango** [comment]
closing this issue
