### ISSUE TITLE
Minor - Sidebar menu and sidebar toggle not working when it minimize

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-admin-portal#85]
Issue: Sidenav not showing when i minimize the browser.
Module: Dashboard

Expected Result:
Can clickable the Sidebar menu and sidebar toggle.
![SideBar](https://user-images.githubusercontent.com/34052250/54969358-bde52a80-4fb8-11e9-9df1-3935819170c2.PNG)

**Comment by abalita** [comment]
- Fixed.For testing v0.1.24
- Modified File(s): fda-admin-portal/src/layout/UserLayout.vue 
- Resolution:
Added v-model for v-navigation-drawer
`<v-navigation-drawer app :mini-variant="mini" width="250" v-model="showNav">
...
</v-navigation-drawer>`

**Comment by VPBelo** [comment]
Closing this issue.
