### ISSUE TITLE
Unable to add data in Admin table.

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-admin-portal#86]
Issue: Unable to add and edit admin data.
###  **error: lenght of undefined**
 - Actual Result
![error3](https://user-images.githubusercontent.com/34052250/55209702-e1a9aa00-521e-11e9-8715-5015088b346b.PNG)

**Comment by abalita** [comment]
- Fixed. For testing v0.1.26
- Resolution: Fixed error in validation

**Comment by VPBelo** [comment]
Closing this issue.
Credentials:
Username: admin_mark
Password: Admin123

  - Actual Result

![adminNew1](https://user-images.githubusercontent.com/34052250/55461197-6f720480-5626-11e9-83b6-c1a7d14085d0.PNG)
![adminNew2](https://user-images.githubusercontent.com/34052250/55461198-700a9b00-5626-11e9-9b06-02f6c18d1524.PNG)
