### ISSUE TITLE
Unable to add  Fees in fee table.

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-admin-portal#87]
**Issue:** Unable to add and edit fees data.
###  **error: Uncaught (In promise)**
 - Actual Result
![error4](https://user-images.githubusercontent.com/34052250/55209755-2e8d8080-521f-11e9-8dda-e037ffd6ecf4.PNG)

**Comment by abalita** [comment]
- Fixed. Retest on current version v0.1.25
 - Modified file(s): fda-services-payments/api/dao/FeeDao.js
 - Resolution: fixed 'ReferenceError: fee is not defined'

**Comment by VPBelo** [comment]
Closing this issue.
Credentials:
Username: admin_mark
Password: Admin123

  - Actual Result

![Fees1](https://user-images.githubusercontent.com/34052250/55460949-cfb47680-5625-11e9-8f10-19f7eecbef49.PNG)
![Fees2](https://user-images.githubusercontent.com/34052250/55460950-d04d0d00-5625-11e9-99c6-ecd1c1e8756b.PNG)
