### ISSUE TITLE
Task - Start/End Process

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#89]
**Scene: Remove a selection of start/end process in task. Tried to neither start nor end process is selected**

- Expected Result: 
- [ ] Can remove selection in both start/end process. 
**Note:** Task can be also not a start or end process.

- Actual Result:
Can't remove selection on both.

![image](https://user-images.githubusercontent.com/34019450/55300886-6ccbaf80-546c-11e9-8001-09edee69e901.png)

**Comment by kyango** [comment]
fda-admin-portal/app/task/task
fixed and change radio button to checkbox

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![EndProcess](https://user-images.githubusercontent.com/34052250/55530800-2c716900-56da-11e9-94d3-ab94af361d68.PNG)
