### ISSUE TITLE
Task - Validation

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#90]
**Scene: Tried to edit a task**

- Expected Result:
- [ ] Can edit a task. 

- Actual Result:
Always prompting a message `You have inputed an existing details` even setting in start process is the only thing that I did.

![image](https://user-images.githubusercontent.com/34019450/55301106-73a6f200-546d-11e9-96d9-b38fd1eda749.png)

**Comment by kyango** [comment]
fda-admin-portal/app/task/task
Fixed can now save edited task

**Comment by VPBelo** [comment]
Closing this issue.
  - Actual Result

![EndProcess](https://user-images.githubusercontent.com/34052250/55537831-a4965980-56ef-11e9-883f-ef3aba54cb43.PNG)
![tasks](https://user-images.githubusercontent.com/34052250/55537839-a9f3a400-56ef-11e9-9538-0b0cf438adb5.PNG)
